server:
  port: 7002

spring:
  application:
    name: PRODUCT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  management:
    tracing:
      sampling:
        probability: 1.0

eureka:
  instance:
    hostname: eureka-0
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local.8761/eureka

